services:
  web:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./flask_server/:/app
  
  chat_server:
    build:
      context: ./chat_server
      dockerfile: Dockerfile
    ports:
      - 9000:9000

  mysql:
    container_name: mysql_container
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 9090:3306