apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  labels:
    app: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat-server
        image: gracianojr/chat_server
        ports:
        - containerPort: 9000